# Generated by Django 4.2.16 on 2026-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (.xlsx)')], default='xlsx', max_length=10)),
                ('home_address', models.CharField(blank=True, help_text='Visits whose name/address contain this text are hidden from the dashboard by default (e.g. your home address).', max_length=500)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('visit', 'Visit'), ('drive', 'Drive')], max_length=10)),
                ('source', models.CharField(choices=[('google', 'Google Timeline'), ('manual', 'Manual Entry')], default='manual', max_length=10)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('visit_date', models.DateField(db_index=True)),
                ('parts_used', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['visit_date', 'start_time'], name='tracker_tim_visit_d_53ddc7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='timelineentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'visit')), fields=('source', 'place_id', 'start_time'), name='unique_visit_per_place_start'),
        ),
        migrations.AddConstraint(
            model_name='timelineentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'drive')), fields=('source', 'start_time'), name='unique_drive_per_start'),
        ),
    ]
